version: 2

sources:
  - name: raw
    database: QUICKDB
    schema: raw

    tables:

      - name: trips
        config:
          loaded_at_field: pickup_time
          freshness:
            warn_after: {count: 30, period: day}
            error_after: {count: 60, period: day}

      - name: payments
        

      - name: weather
        

      - name: riders
       

      - name: drivers
        

